[dependencies]
  di = {path = "../", version = "1.0.0"}

[package]
  cjc-version = "0.34.3"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "di_demo"
  output-type = "executable"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
