[dependencies]

[package]
  cjc-version = "1.0.0"
  compile-option = "-Woff unused"
  description = "nothing here"
  link-option = ""
  name = "di"
  output-type = "static"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
